# Generated by Django 5.1.6 on 2025-02-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_state',
        ),
    ]
