# Generated by Django 5.1.6 on 2025-02-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0001_initial'),
    ]

    operations = [
    ]
