# Generated by Django 5.1.6 on 2025-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0002_booking_payment_delete_user_booking_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
    ]
