# Generated by Django 5.1.6 on 2025-02-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0003_worker_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='servicecatagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='homecare_app.service'),
        ),
    ]
