# Generated by Django 5.1.6 on 2025-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0005_remove_worker_worker_address_worker_worker_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
