# Generated by Django 5.1.6 on 2025-02-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0002_auto_20250227_2125'),
        ('homecare_app', '0005_remove_worker_worker_address_worker_worker_district_and_more'),
    ]

    operations = [
    ]
