# Generated by Django 5.1.6 on 2025-02-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0006_worker_worker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
